### ISSUE TITLE
Error 404 for Patch Notes in Blizzard Blog

### ISSUE THREAD

**Issue by Elitesparkle** [stuaroo/heroes-patch-notes#2]
There are two types of links to Patch Notes:

- blog (eg. https://heroesofthestorm.blizzard.com/en-us/blog/21159501)
- news (eg. https://news.blizzard.com/en-us/heroes-of-the-storm/21159501)

All links in the blog format give error 404 due to Blizzard changing their site.

You can easily convert them from blog to news with string manipulation.

**Comment by stuaroo** [comment]
I did not expect them to just 404 everything going to blog instead of adding redirects, that's kinda wild.  

I also noticed that even older patch notes pointing at blog via battle.net (e.g. https://us.battle.net/heroes/en/blog) will redirect but it's to the now defunct https://heroesofthestorm.blizzard.com/en-us/blog instead of the news site where everything is.

These are easy changes so I'll be updating all blog links shortly to point to news.

Also, somehow I never saw your original issue #1 on missing patches.  I've been outta the scene for a good long while now, and hadn't realized the game was still getting occasional patches.  I'll start working on adding these, but it may take a little bit as I'll have to figure out how everything works again.
